
# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "0b0661652a064c48f5ec565b596cf3be1a438e9e1bd1de551f16f76172ae0a02628a5cecdd366aaba070786c2040c32113da871ca3a80d26902eb7566a319d6f00"
genesis_address_str = "2LuKycJ7SQwbSxoX65Bu8BwZ66RegDaWGK"
blockchain_pubkey_str = "0278d26405ec24c8bf8998cf767b65c29f0dfcdff3542cdb1de44ed0539e9c9d9b"
blockchain_seckey_str = ""
genesis_timestamp = 1426562704
genesis_coin_volume = 200e12
default_connections = [
    "192.243.100.192:6660",
    "167.114.97.165:6660",
    "198.245.62.172:6660",
    "198.100.144.39:6660",
    "94.23.56.111:6660",
]
peer_list_url = "https://cantdoevil.com/blockchain/peers.txt"
port = 6660
web_interface_port = 6420
# unconfirmed_burn_factor = 10
# unconfirmed_max_transaction_size = 32 * 1024
# unconfirmed_max_decimals = 3
# create_block_burn_factor = 10
# create_block_max_transaction_size = 32 * 1024
# create_block_max_decimals = 3
# max_block_transactions_size = 32 * 1024
display_name = "PrivateNess"
ticker = "NESS"
coin_hours_display_name = "Coin Hours"
coin_hours_display_name_singular = "Coin Hour"
coin_hours_ticker = "HNESS"
qr_uri_prefix = "privateness"
explorer_url = "https://explorer.privateness.network"
# bip44_coin = 8000

[params]
max_coin_supply = 2e8
initial_unlocked_count = 50
# unlock_address_rate = 5
# unlock_time_interval = 60 * 60 * 24 * 365
# user_max_decimals = 3
# user_max_transaction_size = 32 * 1024
user_burn_factor = 0
distribution_addresses = [
"2LuKycJ7SQwbSxoX65Bu8BwZ66RegDaWGK",
"QsRSo9f9E4Kr3BTHYj5ZgDkdfzX96dUXnE",
"21h9d38yYJhgGWWo3SnVMqmWooVy1QNv2aD",
"mJADK8t8aA79ggoFHnYZQ8eWDEZxQrrn8i",
"2efzoYJkgRqXYHdnRMv9iQFF3QbmtPxZAJL",
"ad9Fga3SExoyHbfm3DSuRsdXge8L1QBvrW",
"nmXCEtFjVX9S9FZETzdKQ14Ry4a9Wb65Eh",
"4gvfhUg89X1dGW1aGpyZNd648d8Ld9vbRw",
"gSDLsotvPmEDJ4EyiR7cWkWeYMVvv5PPcU",
"2P3bn86kDuEkA2pX9DapfC2L1v9uNECP5NM",
"2FsGsNGdPPg1k5CQh3p25nC5Xx7a285ZpDP",
"FiqnAiwvawTrdem9fR55mNEPzhDoehuvZE",
"VjoVnJprurDbn1WCnsrrLvS3E1Ad8h3P74",
"EWLCqGgosVz2pfyfh8CRdjRM2FRRqMGkPS",
"2RhjMk8KUdb69785S1xmW43KDXggYwZAhfo",
"noXFkEowNZUdGJQedMbPf3VD7fvmsiyZwb",
"L399iwHJ3FPYD7w3SGGxtsNRYJmKKiJoTQ",
"nQnDQEsVkxDtXnkfSqsVY7CWGU7nRh62sc",
"H71YtFpTmvZz1mzTyyVAg4v5NSHM28LK3N",
"YLfhZt1BnfrmUpegDCzrJZMht1pn4dGtt4",
"gVMYqtdNrRmi1z1MEvNXRm2EopQGizsjiv",
"2LUnMwZZuiMyfoj8TaMRtyMtKbm2Uu38esr",
"2AmZWAYUasP1pCr5f6xwwnMAkGEmN89a4Wn",
"WrFZLSyZ2bTwtQY1La3JhQRGbEhtvCSg8D",
"4EUxNewR4b8bXf5kpmFCWdTEr4d3y1GmEt",
"2NwGsfwXNU3kEP1zq3cMdH8oMxc78qeGVfM",
"2cw5bjqeQebBG6UVLrhriDNG7yQTdEVSb4Z",
"22DNvs3NnW1NSzA4tfVBRBGmh41BhBKeDfi",
"iBsqY7gEDc8TfVq58cGsGzKtfLgppCmFTj",
"2HVBwCxdLWxKo4mhffXP4cGR19Xif5LkwC2",
"A3A5mMF3rkjrSp7YBSryAbT5viVj1c2vHp",
"2bnDLjzdWPDGimr32c1PF3HGVH2L3GSraR7",
"2Uz6NPPhXfTRK2242B47gVYZ6hWtksVsNjE",
"p5RamSyZX6id6wXNhcpxCnwUb8PQ2JzG4n",
"C488ycT9T8KUcyuysRMU8Np524KNj4XDt1",
"2WNxsfuLVqvZrkbkwk9w45yEVz1keFkRQaJ",
"8P84GZiPHtpZCQUxtDnm9GYuYXuyguypfQ",
"RM6kSJmHLdUtAGnUKj3FNZ11oJEV5oRBSk",
"hYT4SdFeERtVadBNhtyoHABGHsMsyhgYqS",
"2Xd5BDG7yxs9KAibNrvhZhvzEy84fDg5UN2",
"eQw1v2q6hXADjH7jUeyUKUpz1BXgsEvsqZ",
"232FQf9VKjjJhtai3JMWwjF4xHEtjmvUt4s",
"6Prq889hYvnYJzkoVXYdBoTVyN85fe38uB",
"7f5Bofm2TqPAWGgyGYSkAuQFSbjVTyL9rH",
"yK4ESmScjk7tzPjAiUfhAJvVhGk4LeMPTy",
"25XgipsRtDhdBartUCnvXDddxgFrbvq14T",
"27VDRSMWPrN4Hw1haQzR8hiejK8sFb5kyL7",
"2KgSfcVf1yQBp9eryKreV27SvMD1ePW91BU",
"eQx9UHqY6fnfYdX1cwuxSywdN1TLofV5gV",
"MGEqH1nMtMREceJ2aRpeC6nxVLJXxJD4Rr",
"6H6CVmoT65uMGDiMxT5RZijbcSo9yWVq2X",
"2NDbgEj5pbocSknpKu38hhvVpfq7sVNhCGa",
"xZUsKC6CzVWvTsyRDw5mJckD8EzdnHvgQv",
"2MBHaEg8esJtY1t1sSVEeZeoH4udYC7d3mE",
"2FRjRDaoCXfwmb9g1seLVibT5pi8hD7s4c9",
"2VXgapMkFfsmNGsNWsExwt5aEkv87udgmRe",
"KKw1AH7onPTGMyfLNiPPGbBShK9ojTMLCx",
"2Lai1hmHsxFMWMaMYjsWqioYFg6uP3LGasZ",
"22NBm44TtLwWN9NvyNoUUPBDcz78zNcRrjR",
"219wtnZd64nD8k2AdJR7sBq2T1VrGKZRTpv",
"De2prgdvUQznqYZaSuN3NY8tXaun9Agcyg",
"zdeHGoATW5a8Sr2wLfEznvk7NKJEMhCNv6",
"aCdKodqM2TcbZawbrWXMy6mN9BhhfXGg2p",
"2mWFiX69UjSqepaLxLpQW6zBRPMLk8FqvNW",
"Ft94KbWXzuqDXHeN5ns2J8jPiVLKywHLvL",
"uo9DNVMBq7xtWvEeBMpBGMF8c2teWmAtHE",
"2L1FzXX6a6tBS5zb98S5Pg3vGX7EQWqz3x9",
"hVcrMGW39nmnYKqDLoMc2B6KqwbUN4pXig",
"Yo2zr7Sfyg5b2NtFiuBJTejRESkWQhJHf8",
"Kju1yZxBTebpZHTBjcRMoXvS9GQ9TDhJmi",
"2DFHm3YqdM2wuZGby3NeTFT8ANt5TDqSFNk",
"2XSQZBPNpC86AnQiqCpm6MygrKfnfNt7ADn",
"mcTTXYuszGD56ajh6mAkq7WBxVuwLhCziR",
"s6xFUn9Uv5szsedfmNpwB2F2HqkeCGrsvf",
"22MUQjAD24QVAYMSy2PkHXFG1hhYQXT9hGH",
"2U4hgBRwfj9C27DjXnQh2zH8A4v3DRp45bZ",
"28eVhXexpWhw193DxP4i4NY2P9Tv24KEyzh",
"2HjKe2GBuLC8XE9wDjMuvVWj8cJKJosRUiM",
"wfZ2FHzphjLQRAkRfYuAgoxwmobSL1ZUqQ",
"NuqQyUgZbnYZEiz8FrfTo92UGvXYvn7Zk9",
"4Mo7N1xQP4YLQhWQ3ECP5JdSCtaat4DAWW",
"2K6CjhvWwK2fQ9BgHZgdA6srYbMDEuwo4eL",
"29mJaVr5c4bgSwqR9qbrRWFSFNFbQpjhHBw",
"z7XmnmhxYXbh2S873NbERJUNThUQ2mw3Pz",
"2F8HefCS7WLb4xFUVZE65synvGd6dCT4vyY",
"2UEPMsgqB8hYNDR9H5De5HKLgaFVzQyJqrj",
"57HJnDrL1MNcpnjHmk1x9ap2ejqvfofBZL",
"2gsaBv3RM8qgR5u5qFfZyy7VgEnahieoVaA",
"2KUE1xTEPwoswMmpYkdfLkXXjxBVmk5RPza",
"6gWXzTdM9uUdbHP6XVnyw3WrVNc5AT7SAF",
"piZCCRx3jh8u6F7A25xtgKGUwaoqKmgwW9",
"2Eg2kZLcgKTv7gkb3SiCoPdhcm1i4YNjvpe",
"N39futUKGiKdaKYLC4ntecaGwgq3CiD9b9",
"pwpHdzP1aiF3riKbTPhULqrhJErq5tQ4LN",
"oK2cQrxCQzoTwTPEPURMTkbXjW64g7CEee",
"2mQmSFMsSxMcLQmyFnha7bM8FziPMBYvR3W",
"2Gqc5Vz6TKtnpdSQayd5JFALckA4Zc6LPP9",
"6LmP3NPSVtbTSwNSdpGvkseMUAXmoNqwj4",
"2E8CUubo4YCKMDnANVaZBF5zD8EWN5gPP3A",
"2ffKfjYxr2S3xREVWsCBViTkGwnduzhDsCc",
"2EBixsJgitNV72B8E1eDeRT2kxaCRZ5tFLG",
"tWFgcCPZFrvxUi1scjPSJSu5dRPQCdU3gj",
"gvQ5pzj5PpjkGPgCwp9GRHBseZj9WbwikR",
"29Cb4ZHZBP61R8Lcz1spuQJi9be7JPsY9LV",
"5F5QbpMgwfuGiEg7kQYrnCi9UQzQFaM5y4",
"ugXG5F2aK9ETtPaQvX8b8oTLaNak6iZLmY",
"2Zw7JWkwnkLNwVyRa8RpCtCD2DsnPvPSVPe",
"2fyNHB1WB6TaY25QsAAfWN7SKRmmcR3w6Yg",
"X5cScxYfRFrMmzQvK8qnsuf21Kro4KWye6",
"2dzx4Z2PSJuRn4bEjvcpY2vQVFDUN7zwURQ",
"dtjNcJ3KFVYuRugtQZ6iWJht3o3B99wHsZ",
"gbLNjm6Hhsk5YbZiEzLfTWbuy6Z1xNBjGL",
"rMwNqCpq55Wvv59idRNoA9RRXB9sGVFipQ",
"ajEYL54xQKCi4y7otPjHER53bUa6HR2ffn",
"2VgkbhBQ5yTDNsi7XeZ3pBfe75hFdGspJud",
"MdsaRkfzXatgP8ZTVnEZWNr55NER6n3oMo",
"2FnTLku9QtfhTYwHcJmUgyMJpo4Cw3byR1x",
"ET4a98Kf1dxnUEWsuiDS7RkWFSgqf33k9K",
"27Px3PXfWvzHHjeSdTyxWMX6MfRezVXmNaA",
"NB1wS5y65VhExqBQecVg8Vs1og3KcbUqpY",
"279VmDY6ad9w8N9B1iGVMsYpkYqbVDC7uzB",
"ZNYu6kGR7PCZw3SWbD3W6qXHaXaYxyJcma",
"32fH6LyHrjBiMA9jw5YQT5u8QYAcPXJ6vz",
"2N31d8n2JnbFBm9cJkgB4RL11mTbAuhSzLY",
"NfekRpaM5RvkreKjjtCNHaavfkSPrTvhtZ",
"2fcXjs6t7R4Sf7T787Pae15WYahRAo4UXBZ",
"2hT6dCpBN5MbD8THDf6XdS5171GjMFnobYT",
"yN6w56gMzMzm1noE52yiZvhXhXffUwkuQc",
"N869RrDhXyjRKp8m7VHDKN9e1vJ33HmTYc",
"2Jm4TijanyfqsB6kRbGjxj2SgUsrVr2UVQu",
"hE6MxvRroCmKVbtzVyEgyQhRq73s8JBpgc",
"2hEHSVtdHHqpZrZ7s2abdyTrQjUW71EvLhK",
"66s1Vb1ng9kP9DxaNsmjEj49w15AUU2mXA",
"2aRaUt3kUjFyYbdEmiVoMH2GeSd8zSdHuoy",
"HLu8cth3yGf5D1r8BvxJX5gBRuzEKMjF6W",
"h1oZaAnucR7DHn347J7pZH2YKAJsftACDf",
"CqU1E6TLD7MN1VMCm9qPLAeJQ8pmXFQMW2",
"2EQ9tQErUdnwLGEjCoUwXeU5bhQi2Q18TeV",
"2ea4i9Qd1bsBgg4pUfsUdoFiPXMWdQEsFDp",
"4rKNPdstVAAGrsJ5Kugo9oeiW3NsY1D39r",
"2g9WsBeU8J7hqkTh57zDuMtmHfX7XwMdmxP",
"2R4xZJVSHsyzN6ywAdDx8HKqVJaqDBJLv5Z",
"2Y8ed281rzHmXo83AgLcgomJasgzcCp3u5v",
"eHGxRGMUAr2NhJsiWqThBR6DZyBjTJf1mW",
"yGx21zj5UsWVJ4yMAsxydzXhHReBfQ57UZ",
"t1FBBzkHfzWqXdcayYVy3ADvPEhpuVLC9t",
"sCiCVmqtizJAoNHt1J7bqooxJwt9tyCEcN",
"2cyuJ1YpsVNta46NQB1aoJLsK6D4gTgvJU7",
"E2WppkRJUiNh67qxPZYLrjBGAAWDYAgK7A",
"29PicJt9C3GLYvcGfPAMG7Ye9H32AXe5jZN",
"2b3D8KkRJYpcaRMJ2CLwAcNagp2EF7zazBS",
"qSmBESuoNCHES8AAjCEQscAtDqzQXNWjmW",
"2BVMwX3CCb435AYFvo9jsX7pTRWUoM2uRea",
"2YZ2w8kbXPU5974WTBzMTJx1UCX5NEmnx14",
"CFCeVxctYuPRi87dnVEjCYUSLo13PWqgZq",
"eQjxqz4gxyVHUCZ5rRcd5vHiu2MBK5FWXk",
"4maccKJ7xSpP42XAH4cDKBnNrbySc5JHse",
"24z4nFgisCkJV3RGPoPuSWMR21yDNhifkV3",
"92iDqk8hN2ZXBDqDKuGuYqMcejcTKNBKV3",
"Fwy7XE5asSanyHD4t6GxJfZDD1oZhYp24n",
"xh3dkRAX7db7L47XZFtia4kA4gMDfjDRY3",
"uGxmmT7EsFMreArszRsfLr7Dhi6cUmKFUy",
"oWJhsnWXVzK4WhsiUmS8b2RC5eTGVb2JWz",
"23J9QQeuPTqEZzsm8raB5f5dCcTaCEK1ZpP",
"2jrhEkGM4YqorN4r6fsDe3HPydt2f49ETkb",
"nGED22ctjjkXWcLqqeGMXPCGt3iD3frxny",
"497UYmqykm88q1LPBaPznMs3QhiCvLbjbm",
"2CZKhSPHBZSEEhunuw15srefwVZtyQDTZa7",
"JSrqHJ4XjB7SsH3U7sHsut1mWVNnwCR2RK",
"E7SuxFbVqTUtXxDvudiTFWrGSKa3ZhYoft",
"3X54ycDz1u2dX8UnXhoP3pyYzs3TmE1S8o",
"2Tak7xTNsoSP5ZUdVeuJuUiy7cBgHXnE6BR",
"X5CWQHs2Xrtdnsxjt4MDRyNM6jomudEgwo",
"2YQ2MZj784LzsAwWPZb4XfrS1upm9UxknBW",
"oAYfSnFC8nH9TYmJKJ2YBRq6yh2tKErb9C",
"rGgKVakZDaqQ67woBzEzP3d2geQrSxDveG",
"4WyH6Y5kqXp2qgSjnnyFrpaHTYF5hkqY3K",
"2j7NNZBiBE7TWRW6VSKSrVce52jnmFt2ZUG",
"rKtRstLksovuPr5BB1zNazHwQFM3bs4Fn4",
"JdDeeq58iWgjDmtgfF91Pvs117giepyAqt",
"24NTiQYAj59gRUZkspTnDUULpviibjMh9ym",
"2Yvht852VxErPMP77drn6PEiDtRwGjXYLsZ",
"2brsFaTDAMkf3LxM2WDu4Cv5Sdqh5oNWU8i",
"2KnpFqmnQGxcQHxbWLgjs2VfGQWDCMaqAjk",
"ms3M9TCZmhEHnD9XCKw6rdteyACTSKZh1d",
"9fFEiB3ukxuVZjXuA2RyTpwdGWHUYPMEkF",
"24yByJJa28iSkAWHgzgZUeRsfpHxuqcT61Y",
"2YvC9cSk4f2c4mxcszXbF7PvERVdvQAdzLS",
"mWcpS9i7ixEdqcDvXwprfbMoM8uvKwCnm5",
"uaNdoYD3axyktSyLd4HJ5ju8CboMdJ8o51",
"2AVSi3ucRwEqchoZxu5bmXsKWg2yYnHVB33",
"2iBa69JvDUX7G6Ltdn8TdcfdT2PXjML2dfn",
"2g8Kpkc3vmD8Vtumm3Mv6G8sEJ7AcqvSKrQ",
"2hFG5PZjFVoH9hVUgwqeYnk9kSttj4NJdgm",
"KWUG6MRrwJZKsVyojYP78F3RYeatUH7WzL",
"vbwy22NNa8W93RssChgZrDD5SpL4d3eGzd",
"2QwuvRQduPX9R3eJGY3vJAAc2Y3pyPJG1xk",
"KcjtCazAV7fCnyDDyYcVfuBTmkK3KEj1Yk",
"29eAmDGRNw5bxyi3wCBQTEFzr1ksTzFJknR",
"m9Hvxc5x2sHEjQf8VaP2xemwG4j7ryKekv",
]

