
# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "20245614df0bc55f761d81f125274654dd084d2ca0f933038fe16ba8c6e53859623d172269392e020acab208194e21ae591d3b357e1fdee44b7130136d732eac01"
genesis_address_str = "2eQpkfb6QYYWrMujCZobMGHRus1WZ9pNM2P"
blockchain_pubkey_str = "022d894c92ac54c10e18a4831d3630336f8c14dcda231327be73df285450ed6d24"
blockchain_seckey_str = ""
genesis_timestamp = 1426562704
genesis_coin_volume = 200e12
default_connections = [
    "192.243.100.192:6660",
    "167.114.97.165:6660",
    "198.245.62.172:6660",
    "198.100.144.39:6660",
    "94.23.56.111:6660",
]
peer_list_url = "http://cantdoevil.com/blockchain/peers.txt"
port = 6660
web_interface_port = 6420
# web_interface_addr = "127.0.0.1"
# unconfirmed_burn_factor = 10
# unconfirmed_max_transaction_size = 32 * 1024
# unconfirmed_max_decimals = 3
# create_block_burn_factor = 10
# create_block_max_transaction_size = 32 * 1024
# create_block_max_decimals = 3
# max_block_transactions_size = 32 * 1024
display_name = "PrivateNess"
ticker = "NESS"
coin_hours_display_name = "Coin Hours"
coin_hours_display_name_singular = "Coin Hour"
coin_hours_ticker = "HNESS"
qr_uri_prefix = "privateness"
explorer_url = "https://explorer.privateness.network"
# bip44_coin = 8000

[params]
max_coin_supply = 2e8
initial_unlocked_count = 50
unlock_address_rate = 5
# unlock_time_interval = 60 * 60 * 24 * 365
# user_max_decimals = 3
# user_max_transaction_size = 32 * 1024
user_burn_factor = 0
distribution_addresses = [
"2A5D7GW7kCgRXfZseNq98gn4uVPvtv3ptip",
"2fXASD4uA7LmKHiEzp5kTnt37WLmQameNa3",
"2Dw5Jh66aJ2CNYtRUr2d3gJKVYiXeG5LKkq",
"2B3PoAhndBptKWJCQwdhXCBJAUxY5W7778Q",
"22KDHqxzBabGdWXBuTNKHyUXE3e4r3Lo1gZ",
"23kURrdpM31x4f9qZAusxaX7Zf1g4rvhRms",
"UthdxtRew8yTdQV2zLFgd3mHR7YAs8syAg",
"2MeEbvsNkbLxNRitYQHEujbNjWS4iVi9Qbd",
"RPeGtPRpPjhX8EGMmNTaRWY6jRaaRtGWJF",
"pzGQ1vpkWJnGeL6N1JSJQNG2Vq4rK9ZarC",
"25QDzPKG7jxh8s8MKp6UhxVtrMeRtrdujte",
"U5LSqbR8HqBqpRzFKFn5GZX7MEugmqKCaS",
"2BjGcRrGfc6ew1n9hQ7too7vZdaaWVx5JmQ",
"2bak7fZTYyzrUg5UPDS1QbnmCkC3qZojF6S",
"2dheM1DD93pDUns6HWYon7LHAJX5k5frkhr",
"2EyafEfp1skDcatfSso92ekYDoNLEf9JYrp",
"pebdeeqmXcJsjMfciXcS1u6we9s2yf41Jg",
"2SANb9PPDWzw98wmzREBnCNr9HM6Uop5nvG",
"ZE8RnQ7gt8bLdqPLP1CmsMTV9DGddewWcp",
"2jHAd4pXGLQgdSPJQEDju9edA6gZV367Uvj",
"2MmmByDpd7RjEwAMCW21SYJWmaCMyLTWYtG",
"2Lii5Vszuz794ax4Dp2HNaQcssZKQozZtn3",
"Lhdg8NogJuUSJP5MtVHWtnM6FvrLvTiJmG",
"2YgqYRCAMRMr9EczH3T5JK6pj9DpEjcWRw5",
"2dedUDcYVo2L58pFgZqzNQQ8sLjeBdKb9cH",
"2KSdfRefQfdEGjLf4TpjUDcFJDPnkWe2e7t",
"2Njc9QqpAtsFsqm9pb3g8NyE2cSMRHG5qGx",
"rkRRCdznhJ6EpkWbTUmqR9KgbAS3TnCb6t",
"2KHC4ZiR5X68vq1jnkwJ5E5HPciruSWrdA1",
"VvLJiLn48yy9SQgWt3t6RRiDp1NBnBA8VS",
"yE94Ad9yFhizkwJjZZKKbiXfCe1DFqpfcL",
"29LaNED62wzAXoUQLJ2YSRv5k67XP1Bj6V4",
"XsP7Q98A2EfKNLmiwvwqEaHq4PZBgKHQcU",
"2VH2DZm9qABYzwEqFZETvyACPXHkxsy9grd",
"UqUJahudkG39KvGDohivaQ2tc7XLG21gXT",
"BqvK2WJQSuYEV1itEMddZTb5FQdDvfkmoE",
"2eAqGZEcXkJDJssqqxg3fR5biUrx3NKv4Yt",
"4swRp7LG9hRhGsrEgBTUvpFp7Y6RaX595U",
"2PBDcUXn5ZPFRjEAvnctVTX36S6togH179C",
"2cJ6MKyLCD3a5HztS9tTF2H4AsFiTnodV1W",
"c6a7QCc7HeFznwBA696qT9ZiZed2msjTLn",
"2eeEb7YYRmjrUWm1kGdU4jYTrXy4fn5GmHF",
"nKZycQQYHLJAiFQm1WfrDucgTMhJk4vyXa",
"g9aFEtqvF2YaRDeeU9otig4SVao2FDNoA8",
"mcLyMuCp12KZSaFx1H9tM888TLCpiysty9",
"iHd1eza7P9MMJqveauQLuAQ2qgKdpGiEMu",
"2ReJ8in4Z8tWi2yrTX2APsetf6GrUJJwgZX",
"2iA7WMmxpE1CvzFUnuyr7axMnr2aFZNbNvr",
"7671vkV9vFo2NGFBQvNEBTB7nV2fEYdeem",
"28osoF6jYs3D3MnXVE3M5U61cjWKijZYh18",
"hqgokenMB3KTTh97jgugo6QMmeaypdjgTG",
"muubMAXvfaDhgQzzPNT8kPeazYgkbL4Fz9",
"zmkhjjU1Frd6ba9CvoTMpJDeH9XgHiC8aU",
"hi25fJ1mHXKn7rBR2XjHNGBnsWhbyrHBfg",
"KHo8ydgAQTkY6JBKiBRrM6dc2ZBeA6ocr9",
"NRPGgeUa2sfvzeFf3Ad4S3LgU1hZab2eSq",
"2U7EbdGBNDWnBc78tp18zqDsmoSBgw88FCn",
"DuNDM2aXNGjzXhxh3gZJsa9eEKem4zjnHB",
"H5dPvRyLfwXFxFxsmJ635xyo28uttnKxrn",
"2NYDdXxZyccJ36YMR12fu97r5cqH3eNhwNd",
"F887ZYjRATxmsgVt7WvK5HHZDsZqRh6H91",
"vRkvi4toHqGPQ5uzPc8ys4m1394gJyGmnp",
"2fWvNaASszt1RBmRaXpcpZLmPXwQqeBchfv",
"VBjTY5HdUcE1174eBWLu4UTuhWfzndCB7L",
"2VmXnCXyi1KWPEmvdjaA2H4jNy9uW4kKBd2",
"tr6NP7sHzijRNpC8CoNRJCRPJcCeBxHdim",
"G8yMUMxaUo4B8PR4P3zAtSTDaHrbPgNHac",
"53uXPFkyffAA5ThMTmJyR2y43sEL7K5c1o",
"MA79CjN4jgd8Kf13RYLDiQ9aZ37NFrVuca",
"F11WoKaYsm1tT9ZSx33h1L69Bpqw9TsoPA",
"jvS95PFcvTdE7ffAjpLU1ciBXsYtjuEqsj",
"2VMGcgbQA65W7kAJ68GmhBwxnrWYhZxJp3j",
"2a5qWNmnwJef7F9ZN2JcnFHeVDF5MztGUAE",
"2ATDDaDTTKM5vgBdMT4MH9TVwk3ey252GwL",
"A1x28aMp42GqpBS2wovsjsqauoEYZ81gYN",
"2mtAiygj2kc7sr2UDhQrbqfMAYgxAoS8s1r",
"hEBcb1HuvYSWmwvu8UzWWvwXKFDBuFkZvm",
"YGoNn1uJFm9uhGjVbxVhRDFJiSrGD1fbGq",
"sTqMUR6wZJqN6rjHvLjraTZEEJ8uu9eLjp",
"26xcCnNoGSqw2SyBGcaDrv6RwbbNbqP6Tex",
"2RhDiPAQgGSfa7KFPm2iFZi6zoVtb65mSvW",
"2GmUqmU9YzrzcfCLZngXd36ZSVmWrKCaF2U",
"8xCFV5C5GYkf5iZqyEsNij3aVryhbYeMrx",
"NNoQ18aohJ3GjSEg7R3thXB2SK4r1wW6wC",
"2WzVtdS9PUaGAJNnEDpe5uzEGcrbez1Jt7H",
"2LwPQ7VdW3VStLwfVLQ25gUKPfwLKKoesp7",
"rk7npXNZoR7vmyDhxc8wicxymKHhHAn7QY",
"CCCKGL3qHWzQ5FFLnJECFZSeub6NHsX42b",
"RBBKkdQSKbSzLATefc4VCQNgDU29LxE8oa",
"XKRUpzeanvBYwfMcGq5hvvJb4nsuofbYpn",
"2BE2neSPqakGuvcDGhvkp8t43oEWXoabyR3",
"2TJtQ87YHQWcizBSM2frFvXoriTZuu55xXK",
"oUts1WU2SnZEAK7T8YU5Z73GLWUp58vDqB",
"gUNC4R2E3BV9ttL9HAFLXFT1VXoRr3CMMa",
"WVDiKFVG1nZarRE9SttL3yUjKWHtmL1rPe",
"cTagSPdoHEyC4nM1GvoyViDd3RtdKh5sSN",
"oTRPen2Xdb85rf2ZcRiK44os52iXPGyQiY",
"cS9u8PATCaeVar77UGdApe1h2mhTdQ1BgU",
"2cMDJ5N3TBTMnKRyEx7D744wWJM1PQkb8GY",
"Xy7mGPeaZ6qJDWedLfAzJWKyU5HZHSiAGw",
"23M5AJ86CjJmcE7yRmj94fbTkFgwk6xbKf1",
"9MPnebNZaPVMQtPauj5j3Ht3Y6SSWsrS9A",
"CzX8U42JWddMUsXEoFvGgDGpBp3WQCERHN",
"kYdsi8nN55HsKTZwqv8igTrujvfut6PSVB",
"a67173e9UGY2mZdziX2cJHWmGPJ6LGkSZp",
"2m197cUCpYL6vQiD5igtygYiY2Qo3s8mydQ",
"23zaaAsHAhL8VegQVtkysz5jzDA4FxEfxwk",
"pJUcsdkGYbjbFxNyAnXXTd2b2FTa614w58",
"2LtpjN4omyGN1HkJVoG5dh64qe4i9KS74UZ",
"vM2VPmj6aCPCUuLTPe6WpRz9NDuycTPWPj",
"2Vx93GYQMAm5iscEyaFCFZRXj1JUcPG35aR",
"JEtRkbxsBVh8aBsLvQYyaLCJjWwibf7N27",
"F3aE6ewRK2ragjzMz6x1DS2yU5px1Q3C4t",
"2HmNCEkeYDYeoJMUH3rDSpB6v315jBdmHgM",
"KLCSmgfQnPKaXHyN4V1UkxZpGa8gsS2kNd",
"XUgCQNMPBWvWCpRH14gmHaMPMAGtKDwixD",
"264zf9WE4j2WYEnzA5TbLrHKGXzaUVErd8J",
"TH3Kobr3A9Nfek2BDEo6cq5Bsf7tYEN6q1",
"2Z4eYEfEqfFhR6X4WeRUAwZqNcFWwnhU1Nq",
"cux33JvcvrvhnDWuohavHxBQ1o1ytxY3Fc",
"ULW8owAtZDUeewVvmhNXE39TUYrPVGfQa4",
"2SN5Tz7mQieRMj1eQSNSG7LyPg4QKXwRiHy",
"CAPrukM4r3Yb8FpRUPLWESDZbB2dyJdt9H",
"DxVJJivVmanLXprCmyXWSkWqjYnhcjAqZv",
"23A3hkvrKtk1D5AFwzPAbRyVTvuNNtTUGbd",
"2DfHgZpH9EoNBgKrrpVsqDKhZ1UunT4hAtC",
"84hg1D6N82cyGgkSAuhSTtWsCxnad4rL2D",
"zrC3esRdfDgmqEuowAAYuf5oqn1YPzLrqi",
"Yn4V6HJnkhrFgYK2hK4DDybaV7A7dhZjbM",
"DfJmT6VDJDsA22bZRn8Q6PeBpzn7rk8xSW",
"2K1wJFzrz7dn9qwNEhVsCBUocNF9UPo7jGL",
"T5fimZsn8jFZmj3k5MQjmJCHG97Yn5BXjn",
"2cHuqXUUog6U5QJng37sC6eq2HQVAosKzyA",
"2Hf28s7mJzhGn7HpMpLDfAKYpNfhxXRk5nZ",
"cS4UmrAxkxpYJ463PU2T1jkp7MYgRboyJW",
"2XzvHD24piSP1Mo3TFhigSv7oiDNSCvdC6P",
"7B35ERjwNntqa9VePqg8Stst3eo823Ak3P",
"CwcuKLvyeoEGv91dhZpavvQcoE4REfBAur",
"dCR6ZAww7pMct4qEeJRma6yBEmSNAEV2qj",
"2FiK25KJkBFCMieFkW7VxBYAvFKim5o2E17",
"2TUFFQe8VYuZvDLGwJUC4igksc18RCiC7yQ",
"2XHjQ2LwnnmVe1qDD4Ye2jLdWwSrWvw5i81",
"ExUqKCwMA8VeRo6ziU8q6uscAKFDkvb2EB",
"VKFFWZRH6gqNfzurjeSjg6zD4dCKG4FCpd",
"9xTPKN9JLTDJj5s718faj1weENkrjShuTE",
"2YJyRZvQmjyAy5j1pu6LY9qKriuvvW2F6Je",
"5n1YKmtjbkNCsPetBcRZvj33h73iJ2hBap",
"2HXEAx3ZBP9P2cb6PgzXyo5tbHkHGn8j1Xk",
"2h8bo4AUiRPt5DGyKzd3kGF1PcrSFZLGbyu",
"2VbJxrrxvrUPPXsC9pRx3iFjzW2DYbDqNWK",
"2KKPcovGbht3c9KhPFnrRoM6He11XKEdgsw",
"iXMNZgxyJMDJg4vxGmCPmYVtaLHTa3wSnR",
"21sfo9UbpRp3XR8KsXcLh9zq2VX7N3pSqfd",
"2TPeRRRVfsXEwqquywAm93sRJDUC7JeaZnB",
"pqv8FMQz7ZzXrFJCc4sx1cqG88RFbVXo2M",
"2M2UQxiPEjKi1PCS4Fbs72SbqhdzXHGKzTG",
"CcZXRxcAX75Cie8W7n28gwB3f4PNLev1SL",
"7Eqmt5FCoMHuVhd65tRwN11txLWLcB1RSA",
"2NgUpRn3i5yGN6NB5cAmjcPZhUc97Hp1vuT",
"27d25pcKmvtUWfTkPHmsrsZUCwFeW45n3HM",
"J4Gv7UYSoz7fYyPzzZq7dj8MA8mrxEAsXk",
"7DDXityHjL2Mop5paDJm4SCFjiMjrJ3eei",
"PDASxNz9LcfsF1wunqDe6nPBdwURHEgeEK",
"2AjEpabQCA2AeosyUcQRgZSLvKQaxuN36PJ",
"2LHx2Tgyq8bh3SGDYhx73nt2Byt3SnVBYJp",
"SHEgZskpWChPCvhqF9ogVemMrE4tyxWwbA",
"yKtY8XCPHs5xgEcdtfUWk5c692Fdybzf4x",
"2bQcsWVGsW2XvYNuH9W2TF1NraEfzWm83Ra",
"2YZfQFjzRiik35S88H29WNka9n6wN3miGHZ",
"9KdsFuHwVQXt11iQzbRpWPhjusfmDjtind",
"C2G66aawyvnwL5L1VQ6yB3UKrjnswrMfxB",
"yjSefTogUG85qyETtS75iLhVHE4shZ2iqc",
"2Gvam6VBM2VKVguq4bFXq62tWtrvxoFPkfV",
"238nbZ5o2UtgffoJCfH16usFFuXyfbkBuzq",
"2UVbQthov5Q4xGmgedRK5ZDW2nzuBoyPPVg",
"24KZtnLgdaT1rGmRrVJsoqZHRXc6C91hhbe",
"2Z7w2vNfpGMXch9FGKRqtYqX7wcXCtZcryu",
"ujSgV86Yefpt8MoJHJg7vM6ZDQZAjgyYyW",
"YzTgNhYayfpE8oTMf12kawzAUt1FmcEYuM",
"2gGCjHPpkTzKdWu2BEbf2Zn2RSZ2bT6Hygb",
"2kRWB8WZ51d7UHHWkY6nKfsxM7WW6mo635e",
"2FeRLCeuRhDvTYzsouU4DWF14C3p39y7G55",
"25kk7Hy6CgCVWdxebHGzGJy1ZYuvfMUVWop",
"2FMD4epfscgdzYu4z4iaJpLG76nAkVpHbgW",
"2X52LiZgkRwsxRgvYL7T84yq6XnnbttvUVm",
"29jvCKvdq13oWaGZbWpPwuCotsxiq6cGzhf",
"pBuj7rC3t5pZKfpRExK25GrcuFc3gmu14z",
"26qZWzeTGwEwgNdLQ8j6KEKThLgnJhY1a2u",
"53JqKA41w7s1VvRRLQFJQxvvudEk5VBfh1",
"2QcsK3RcxBPeyx6VzSEznJyg8GXxMygmuPd",
"2aa4w3gxQBaPUTt7dVicXFBUuCtjAy9yRwB",
"22zvE2EQpU73CGpS49KFEbcKRxRtjL5uz7d",
"2jKCCEaz7XK5hvifmLUT4LMheoFpzh7dsn5",
"oziJGLaZy1mjiC39Qc2VhKo9NzUiy71sjd",
"gxdaZMDwEGnNHzpPZZDs9fHeZtUNaeZXvi",
"2Zrea5qkdHApRSSG3Q28w7BLSPB5Wo296Uv",
"UHhBdsJRZ8c4ubMnNu5U6unGfKDfn3aePW",
"XUo1fBGujBbhYhjwpcpDgcZyGbRACf8Q6r",
"2AVuqdviQUJELViMdXSSkuExBjdhqa37XP1",
"K1fUZJhQppC7TYsGgC8ErZsy2AkuFZ7jwi",
]
